<?php

namespace SlapperRotation;

interface SlapperInfo {
    /**
     * NOTE FOR DEVELOPERS:
     * CHANGING THIS COULD BREAK THIS PLUGIN!
     * 
     * SUBMITTING PULL REQUEST TO CHANGE THIS PLUGIN COMPATIBLE VERSION WILL AUTOMATICALLY CLOSED!
     * YOU ARE WASTING TIME FOR MODIFYING THIS!
     * 
     * THIS FILE WAS AUTO-GENERATED BY PLUGIN!
    **/
    const PLUGIN_NAME = "SlapperRotation";
    const BRANCH = "main";
    const PLUGIN_DESCRIPTION = "Slappers look at players!";
    const MAIN = "SlapperRotation\Main";
    const CONFIG_VERSION = "1.0.1";
    const POCKETMINE_VERSION = "4.2.6";
    const PROTOCOL_VERSION = 486;
    const PLUGIN_VERSION = "2.0.0";
    const VERSION = "v1.0.0";
    const DEFAULT_MAX_DISTANCE = 16;
    const IS_DEVELOPMENT_BUILD = true;
}